export enum Configuration {
  PORT = 'PORT',
  MONGO_DB = 'MONGO_DB',
  MONGO_USER = 'MONGO_USER',
  MONGO_PASSWORD = 'MONGO_PASSWORD',
  MONGO_PORT = 'MONGO_PORT',
  MONGO_HOST = 'MONGO_HOST',
  MONGO_CONNECTION = 'MONGO_CONNECTION',
  API_KEY = 'API_KEY',
  JWT_SECRET = 'JWT_SECRET',
  AMQP_URL = 'AMQP_URL',
  AMQP_QUEUE = 'AMQP_QUEUE',
  AMQP_NAME = 'AMQP_NAME',
}
